[package]
name = "hello-tokio-async-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.46.1", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = { version = "0.7.16", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
